import axios from "axios";
import { fetchUserById } from "./userService"; 
import { api, handleApiError, createAuthenticatedRequest } from '../utils/apiClient';
import { ENDPOINTS, API_BASE_URL } from '../config';
import { StorageKeys } from '../config';

/**
 * Fetch projects for the logged-in user
 */
export const fetchUserProjects = async () => {
  try {
    const userId = getUserId();

    if (!userId) {
      console.error("❌ No user ID found. Please log in again.");
      throw new Error("User ID is missing. Please log in again.");
    }

    console.log(`📡 Fetching projects for user: ${userId}`);

    const response = await api.get(`/Scrum/Projects/User/${userId}`);

    console.log("✅ Projects fetched:", response.data);
    return response.data;
  } catch (error) {
    console.error("❌ Error fetching user projects:", error.response?.data || error.message);
    throw handleApiError(error, 'fetching user projects');
  }
};

// Function to fetch a specific project by ID
export const fetchProjectById = async (projectId) => {
  try {
    const response = await api.get(`${ENDPOINTS.PROJECT}/${projectId}`);
    return response.data;
  } catch (error) {
    console.error('❌ Error fetching project:', error);
    throw error;
  }
};

//function to explicity check to see if a user is project owner or not: 
export const isProjectOwner = async (projectId) => {
  try {
    const project = await fetchProjectById(projectId);
    const currentUserId = getUserId();

    return project.projectOwnerID === currentUserId; // Returns true if user is the owner
  } catch (error) {
    console.error("❌ Error checking project ownership:", error);
    return false; // Default to false on error
  }
};

// Get all project members by project id
export const fetchProjectMembers = async (projectId) => {
  try {
    const response = await api.get(`${ENDPOINTS.PROJECT}/Members/${projectId}`);
    return response.data;
  } catch (error) {
    console.error('❌ Error fetching project members:', error);
    throw error;
  }
};

// Function to store selected project ID in localStorage
export const setSelectedProject = (projectId) => {
  localStorage.setItem(StorageKeys.SELECTED_PROJECT, projectId);
};

export const selectProject = async (projectId) => {
  try {
    setSelectedProject(projectId);
    return true;
  } catch (error) {
    console.error("❌ Error selecting project:", error);
    return false;
  }
};

// Function to get selected project ID from localStorage
export const getSelectedProject = () => {
  try {
    return localStorage.getItem(StorageKeys.SELECTED_PROJECT);
  } catch (error) {
    console.error('Error getting selected project:', error);
    return null;
  }
};

// Function to remove the selected project ID from localStorage
export const clearSelectedProject = () => {
  localStorage.removeItem(StorageKeys.SELECTED_PROJECT);
};

// Function to get JWT token from localStorage
export const getAuthToken = () => {
  return localStorage.getItem(StorageKeys.AUTH_TOKEN);
};

// Function to get stored user ID safely
export const getUserId = () => {
  const userId = localStorage.getItem(StorageKeys.USER_ID);
  if (!userId) {
    console.warn("Warning: User ID not found in localStorage.");
  }
  return userId;
};
// Function to create a new project
export const createProject = async (projectData) => {
  try {
    const token = getAuthToken();
    
    if (!projectData.name || !projectData.projectOwnerID) {
      throw new Error("Project name and owner ID are required");
    }
    
    // Create a proper project object matching the backend model
    const project = {
      id: "", // This will be generated by the backend
      name: projectData.name,
      description: projectData.description || "",
      projectOwnerID: projectData.projectOwnerID
    };
    
    console.log("Creating project:", project);
    
    const response = await axios.post(`${API_BASE_URL}/Scrum/Project/`, project, {
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json"
      }
    });
    
    console.log("Project created successfully:", response);
    return response.data;
  } catch (error) {
    console.error("Error creating project:", error);
    throw error;
  }
};
// Function to join a project using projectId and userId
export const joinProject = async (projectId, userId) => {
  try {
    const token = getAuthToken(); // Retrieve JWT token for authorization

    if (!projectId || !userId) {
      throw new Error("Project ID or User ID is missing.");
    }

    const apiUrl = `${API_BASE_URL}/Scrum/Project/${projectId}/${userId}`; 

    console.log(`🚀 Sending POST request to: ${apiUrl}`);

    const response = await axios.post(apiUrl, {}, {
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
    });

    console.log("✅ Successfully joined project:", response.data);
    return response.data;
  } catch (error) {
    console.error("❌ Error joining project:", error.response?.data || error.message);
    throw error;
  }
};

// Function to leave a project
export const leaveProject = async (projectId) => {
  try {
    const token = getAuthToken();
    const userId = getUserId();

    if (!projectId || !userId) {
      throw new Error("❌ Project ID or User ID is missing.");
    }

    const apiUrl = `${API_BASE_URL}/api/Project/Leave`;
    
    console.log("🚀 Sending request to leave project:", projectId);
    console.log("📤 Payload:", { ProjectID: projectId, UserID: userId });

    const response = await axios.post(apiUrl, 
      { ProjectID: projectId, UserID: userId }, 
      {
        headers: {
          Authorization: `Bearer ${token}`,
          "Content-Type": "application/json",
        },
      }
    );

    console.log("✅ Successfully left project:", response.data);
    
    // Clear selected project since we've left it
    clearSelectedProject();
    
    return response.data;
  } catch (error) {
    console.error("❌ Error leaving project:", error.response?.data || error.message);
    
    // Check for specific error message from backend indicating user is project owner
    if (error.response?.data && 
        typeof error.response.data === 'string' && 
        error.response.data.includes("project owner")) {
      throw new Error("You are the project owner. Please reassign ownership before leaving the project.");
    }
    
    throw new Error(error.response?.data || "Failed to leave the project.");
  }
};

// Function to edit a project (Only for project owner)
export const editProject = async (project) => {
  try {
    const token = getAuthToken();

    if (!project || !project.id) {
      throw new Error("Project data is invalid or missing.");
    }

    const isOwner = await isProjectOwner(project.id);
    if (!isOwner) {
      throw new Error("❌ You are not the project owner. Editing is not allowed.");
    }

    const apiUrl = `${API_BASE_URL}/Scrum/Project`;

    console.log("🔄 Sending update request to:", apiUrl);
    console.log("📤 Payload:", project);

    const response = await axios.put(apiUrl, project, {
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
    });

    console.log("📩 Server Response:", response.data);

    if (response.status !== 200) {
      throw new Error(`Unexpected response status: ${response.status}`);
    }

    return response.data;
  } catch (error) {
    console.error("❌ Error updating project:", error);
    throw error;
  }
};

// Function to remove a member from a project (Only for project owner)
export const removeMemberFromProject = async (projectId, memberId) => {
  try {
    const response = await axios.delete(
      `${ENDPOINTS.MEMBER}/${projectId}/${memberId}`,
      createAuthenticatedRequest()
    );
    return response.data;
  } catch (error) {
    console.error('❌ Error removing member:', error.response?.data || error.message);
    throw error;
  }
};

// Function to delete a project (Only for project owner)
export const deleteProject = async (projectId) => {
  try {
    await api.delete(`${ENDPOINTS.PROJECT}/${projectId}`);
  } catch (error) {
    return handleApiError(error, 'deleting project');
  }
};
//======================================End of Project Service===========================================//

//===================================Beginning of Sprint Service=========================================//
// Function to create a new sprint for a project
export const createSprint = async (sprintData) => {
  try {
    const token = getAuthToken();

    if (!sprintData || !sprintData.projectID) {
      throw new Error("❌ Sprint data is missing or project ID is not provided.");
    }

    const apiUrl = `${API_BASE_URL}/Scrum/Sprint/`;

    console.log("🚀 Sending POST request to create sprint:", apiUrl);
    console.log("📤 Sprint Payload:", sprintData);

    const response = await axios.post(apiUrl, sprintData, {
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
    });

    console.log("✅ Sprint successfully created:", response.data);
    return response.data;
  } catch (error) {
    console.error("❌ Error creating sprint:", error.response?.data || error.message);
    throw error;
  }
};

// Function to create a new task in a sprint
export const createTask = async (taskData) => {
  try {
    const token = getAuthToken();

    if (!taskData || !taskData.sprintID) {
      throw new Error("❌ Task data is missing or Sprint ID is not provided.");
    }

    const apiUrl = `${API_BASE_URL}/Scrum/Task/`;

    console.log("🚀 Sending POST request to create task:", apiUrl);
    console.log("📤 Task Payload:", taskData);

    const response = await axios.post(apiUrl, taskData, {
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
    });

    console.log("✅ Task successfully created:", response.data);
    return response.data;
  } catch (error) {
    console.error("❌ Error creating task:", error.response?.data || error.message);
    throw error;
  }
};

// Function to edit/update an existing sprint
export const editSprint = async (sprintData) => {
  try {
    const token = getAuthToken();

    // Validate sprint data
    if (!sprintData || !sprintData.id || !sprintData.projectID) {
      throw new Error("❌ Sprint data is missing or Sprint ID/Project ID is not provided.");
    }

    // Ensure dates are in ISO format
    const formattedSprintData = {
      id: sprintData.id,
      name: sprintData.name,
      startDate: new Date(sprintData.startDate).toISOString(), // Ensure correct date format
      endDate: new Date(sprintData.endDate).toISOString(),
      isCompleted: sprintData.isCompleted ?? false,
      isStarted: sprintData.isStarted ?? false,
      projectID: sprintData.projectID,
    };

    const apiUrl = `${API_BASE_URL}/Scrum/Sprint/`; 

    console.log("🚀 Sending PUT request to update sprint:", apiUrl);
    console.log("📤 Sprint Payload:", formattedSprintData);

    // Send the request with the correct payload
    const response = await axios.put(apiUrl, formattedSprintData, {
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
    });

    console.log("✅ Sprint successfully updated:", response.data);
    return response.data;
  } catch (error) {
    console.error("❌ Error updating sprint:", error.response?.data || error.message);
    throw error;
  }
};

// Function to edit/update an existing task
export const editTask = async (taskData) => {
  try {
    const token = getAuthToken();

    if (!taskData || !taskData.id) {
      throw new Error("❌ Task data is missing or Task ID is not provided.");
    }

    const apiUrl = `${API_BASE_URL}/Scrum/Task/`; 

    console.log("🚀 Sending PUT request to update task:", apiUrl);
    console.log("📤 Task Payload:", taskData);

    const response = await axios.put(apiUrl, taskData, {
      headers: {
        Authorization: `Bearer ${token}`,
        "Content-Type": "application/json",
      },
    });

    console.log("✅ Task successfully updated:", response.data);
    return response.data;
  } catch (error) {
    console.error("❌ Error updating task:", error.response?.data || error.message);
    throw error;
  }
};

// Function to fetch all tasks for a given sprint
export const fetchSprintTasks = async (sprintId) => {
  try {
    const token = getAuthToken();

    if (!sprintId) {
      throw new Error("❌ Sprint ID is required.");
    }

    const apiUrl = `${API_BASE_URL}/Scrum/Sprint/Tasks/${sprintId}`; 

    console.log("🚀 Fetching tasks for sprint:", sprintId);

    const response = await axios.get(apiUrl, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });

    console.log("✅ Retrieved sprint tasks:", response.data);
    return response.data;
  } catch (error) {
    console.error("❌ Error fetching sprint tasks:", error.response?.data || error.message);
    throw error;
  }
};
// Function to fetch all tasks for a given project
export const fetchProjectTasks = async (projectId) => {
  try {
    const token = getAuthToken();

    if (!projectId) {
      throw new Error("❌ Project ID is required.");
    }

    const apiUrl = `${API_BASE_URL}/Scrum/Project/Tasks/${projectId}`; 

    console.log("🚀 Fetching tasks for project:", projectId);

    const response = await axios.get(apiUrl, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });

    console.log("✅ Retrieved project tasks:", response.data);
    return response.data;
  } catch (error) {
    console.error("❌ Error fetching project tasks:", error.response?.data || error.message);
    throw error;
  }
};

export const fetchProjectTasksWithAssignees = async (projectId) => {
  try {
    const tasks = await fetchProjectTasks(projectId);
    
    // Fetch each user's initials from `fetchUserById`
    const tasksWithAssignees = await Promise.all(tasks.map(async (task) => {
      if (!task.assigneeID) {
        return { ...task, assigneeInitials: "Unassigned" };
      }

      try {
        const user = await fetchUserById(task.assigneeID);
        const initials = `${user.firstName.charAt(0)}${user.lastName.charAt(0)}`;
        return { ...task, assigneeInitials: initials };
      } catch (error) {
        console.error(`Error fetching user for task ${task.id}:`, error);
        return { ...task, assigneeInitials: "??" }; // Default initials in case of error
      }
    }));

    return tasksWithAssignees;
  } catch (error) {
    console.error("❌ Error fetching tasks with assignees:", error);
    throw error;
  }
};

// Function to update task status
export const updateTaskStatus = async (taskId, newStatus) => {
  try {
    const token = getAuthToken();

    if (!taskId) throw new Error("❌ Task ID is required.");
    if (![0, 1, 3].includes(newStatus)) throw new Error("❌ Invalid task status.");

    const apiUrl = `${API_BASE_URL}/Scrum/Task/${taskId}/Status`;

    console.log(`🚀 Updating task ${taskId} status to ${newStatus}`);

    const response = await axios.put(apiUrl, { status: newStatus }, {
      headers: { Authorization: `Bearer ${token}` },
    });

    console.log("✅ Task status updated successfully:", response.data);
    return response.data;
  } catch (error) {
    console.error("❌ Error updating task status:", error.response?.data || error.message);
    throw error;
  }
};

// Function to update task assignee
export const updateTaskAssignee = async (taskId, newAssigneeId) => {
  try {
    const token = getAuthToken();

    if (!taskId) throw new Error("❌ Task ID is required.");
    if (!newAssigneeId) throw new Error("❌ Assignee ID is required.");

    const apiUrl = `${API_BASE_URL}/Scrum/Task/${taskId}/Assignee`;

    console.log(`🚀 Updating task ${taskId} assignee to user ${newAssigneeId}`);

    const response = await axios.put(apiUrl, { assigneeID: newAssigneeId }, {
      headers: { Authorization: `Bearer ${token}` },
    });

    console.log("✅ Task assignee updated successfully:", response.data);
    return response.data;
  } catch (error) {
    console.error("❌ Error updating task assignee:", error.response?.data || error.message);
    throw error;
  }
};

// Function to fetch all sprints for a given project
export const fetchProjectSprints = async (projectId) => {
  try {
    const token = getAuthToken();

    if (!projectId) {
      throw new Error("❌ Project ID is required.");
    }

    const apiUrl = `${API_BASE_URL}/Scrum/Project/Sprints/${projectId}`; 

    console.log("🚀 Fetching sprints for project:", projectId);

    const response = await axios.get(apiUrl, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });

    console.log("✅ Retrieved project sprints:", response.data);
    return response.data;
  } catch (error) {
    console.error("❌ Error fetching project sprints:", error.response?.data || error.message);
    throw error;
  }
};
// Function to fetch a single sprint by its ID
export const fetchSprintById = async (sprintId) => {
  try {
    const token = getAuthToken();

    if (!sprintId) {
      throw new Error("❌ Sprint ID is required.");
    }

    const apiUrl = `${API_BASE_URL}/Scrum/Sprint/${sprintId}`; 

    console.log("🚀 Fetching sprint details for:", sprintId);

    const response = await axios.get(apiUrl, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });

    console.log("✅ Retrieved sprint details:", response.data);
    return response.data;
  } catch (error) {
    console.error("❌ Error fetching sprint:", error.response?.data || error.message);
    throw error;
  }
};
// Function to fetch a single task by its ID
export const fetchTaskById = async (taskId) => {
  try {
    const token = getAuthToken();

    if (!taskId) {
      throw new Error("❌ Task ID is required.");
    }

    const apiUrl = `${API_BASE_URL}/Scrum/Task/${taskId}`; 

    console.log("🚀 Fetching task details for:", taskId);

    const response = await axios.get(apiUrl, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });

    console.log("✅ Retrieved task details:", response.data);
    return response.data;
  } catch (error) {
    console.error("❌ Error fetching task:", error.response?.data || error.message);
    throw error;
  }
};
// Function to delete a task by its ID
export const deleteTask = async (taskId) => {
  try {
    const token = getAuthToken();

    if (!taskId) {
      throw new Error("❌ Task ID is required.");
    }

    const apiUrl = `${API_BASE_URL}/Scrum/Task/${taskId}`; 

    console.log("🚀 Sending DELETE request for task:", taskId);

    const response = await axios.delete(apiUrl, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });

    console.log(`✅ Successfully deleted task: ${taskId}`);
    return response.data;
  } catch (error) {
    console.error("❌ Error deleting task:", error.response?.data || error.message);
    throw error;
  }
};
// Function to delete a sprint by its ID
export const deleteSprint = async (sprintId) => {
  try {
    const token = getAuthToken();

    if (!sprintId) {
      throw new Error("❌ Sprint ID is required.");
    }

    const apiUrl = `${API_BASE_URL}/Scrum/Sprint/${sprintId}`; 

    console.log("🚀 Sending DELETE request for sprint:", sprintId);

    const response = await axios.delete(apiUrl, {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    });

    console.log(`✅ Successfully deleted sprint: ${sprintId}`);
    return response.data;
  } catch (error) {
    console.error("❌ Error deleting sprint:", error.response?.data || error.message);
    throw error;
  }
};
